services:
  - type: web
    name: mediadl
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
